import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/Footer';
import ReduxProvider from '@/providers/reduxProvider';
import TanstackProvider from '@/providers/tanstackProvider';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from '@/providers/authProvider';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/header';
import Sidebar from '@/components/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <ReduxProvider>
            <AuthProvider>
              <ToastContainer />
              <Header />
              <div className='flex'>
                <Sidebar />
                <main className='flex-1'>{children}</main>
              </div>
              <Footer />
            </AuthProvider>
          </ReduxProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
